screen:
  invert: false
  flip: false
ticker:
  updatefrequency: 3600
function: 
  quotesurl: https://www.reddit.com/r/quotes/top/.json?t=month&limit=100
  mode: redditquotes, textfileflash, wordaday, stoic
  weight: 50,0,1,10

